# Generated by Django 2.0.2 on 2021-01-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_remove_goodsimage_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='good_brief',
            new_name='goods_brief',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='good_desc',
            new_name='goods_desc',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='good_num',
            new_name='goods_num',
        ),
    ]
