# Generated by Django 2.0.2 on 2021-01-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20210119_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_brief',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='商品简短描述'),
        ),
    ]
